WebSiteDT/WebSiteDT/WebSiteDT/Controllers/QuanLySanPhamController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using WebSiteDT.Models;

namespace WebSiteDT.Controllers
{
    //[Authorize(Roles = "QuanTri,QuanLySanPham")]
    public class QuanLySanPhamController : Controller
    {
        // GET: QuanLySanPham
        QuanLyBanHangEntities db = new QuanLyBanHangEntities();
        public ActionResult Index()
        {

            return View(db.SanPhams.Where(n => n.DaXoa == false).OrderByDescending(n => n.MaSP));
        }

        [HttpGet]
        public ActionResult TaoMoi()
        {
            //Load dropdownlist nhà cung cấp và dropdownlist loại sp, mã nhà sản xuất
            ViewBag.MaNCC = new SelectList(db.NhaCungCaps.OrderBy(n => n.TenNCC), "MaNCC", "TenNCC");
            ViewBag.MaLoaiSP = new SelectList(db.LoaiSanPhams.OrderBy(n => n.MaLoaiSP), "MaLoaiSP", "TenLoai");
            ViewBag.MaNSX = new SelectList(db.NhaSanXuats.OrderBy(n => n.MaNSX), "MaNSX", "TenNSX");

            return View();
        }
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult TaoMoi(SanPham sp, HttpPostedFileBase[] HinhAnh)
        {
            //Load dropdownlist nhà cung cấp và dropdownlist loại sp, mã nhà sản xuất
            ViewBag.MaNCC = new SelectList(db.NhaCungCaps.OrderBy(n => n.TenNCC), "MaNCC", "TenNCC");
            ViewBag.MaLoaiSP = new SelectList(db.LoaiSanPhams.OrderBy(n => n.MaLoaiSP), "MaLoaiSP", "TenLoai");
            ViewBag.MaNSX = new SelectList(db.NhaSanXuats.OrderBy(n => n.MaNSX), "MaNSX", "TenNSX");
            int loi = 0;
            for (int i = 0; i < HinhAnh.Count(); i++)
            {
                if (HinhAnh[i] != null)
                {
                    //Kiểm tra nội dung hình ảnh
                    if (HinhAnh[i].ContentLength > 0)
                    {
                        //Kiểm tra định dạng hình ảnh
                        if (HinhAnh[i].ContentType != "image/jpeg" && HinhAnh[i].ContentType != "image/png" && HinhAnh[i].ContentType != "image/gif" && HinhAnh[i].ContentType != "image/jpg")
                        {
                            ViewBag.upload += "Hình ảnh" + i + " không hợp lệ <br />";
                            loi++;
                        }
                        else
                        {
                            //Kiểm tra hình ảnh tồn tại

                            //Lấy tên hình ảnh
                            var fileName = Path.GetFileName(HinhAnh[0].FileName);
                            //Lấy hình ảnh chuyển vào thư mục hình ảnh 
                            var path = Path.Combine(Server.MapPath("~/Content/HinhAnhSP"), fileName);
                            //Nếu thư mục chứa hình ảnh đó rồi thì xuất ra thông báo
                            if (System.IO.File.Exists(path))
                            {
                                ViewBag.upload1 = "Hình " + i + "đã tồn tại <br />";
                                loi++;

                            }
                        }
                    }
                }

            }
            if (loi > 0)
            {
                return View(sp);
            }
            sp.HinhAnh = HinhAnh[0].FileName;
            sp.HinhAnh = HinhAnh[1].FileName;
            sp.HinhAnh = HinhAnh[2].FileName;
            sp.HinhAnh = HinhAnh[3].FileName;
            sp.HinhAnh = HinhAnh[4].FileName;


            ////Kiểm tra hình tổn tại trong csdl chưa
            //if (HinhAnh[0].ContentLength > 0)
            //{
            //    //Lấy tên hình ảnh
            //    var fileName = Path.GetFileName(HinhAnh[0].FileName);
            //    //Lấy hình ảnh chuyển vào thư mục hình ảnh 
            //    var path = Path.Combine(Server.MapPath("~/Content/HinhAnhSP"), fileName);
            //    //Nếu thư mục chứa hình ảnh đó rồi thì xuất ra thông báo
            //    if (System.IO.File.Exists(path))
            //    {
            //        ViewBag.upload = "Hình đã tồn tại";
            //        return View();
            //    }
            //    else
            //    {
            //        //Lấy hình ảnh đưa vào thư mục HinhAnhSP
            //        HinhAnh[0].SaveAs(path);
            //        sp.HinhAnh = fileName;

            //    }

            //}
            db.SanPhams.Add(sp);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        //Chỉnh sửa sản phẩm
        [HttpGet]
        public ActionResult ChinhSua(int? id)
        {
            //Lấy sản phẩm cần chỉnh sửa dựa vào id
            if (id == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            SanPham sp = db.SanPhams.SingleOrDefault(n => n.MaSP == id);
            if (sp == null)
            {
                return HttpNotFound();
            }

            //Load dropdownlist nhà cung cấp và dropdownlist loại sp, mã nhà sản xuất
            ViewBag.MaNCC = new SelectList(db.NhaCungCaps.OrderBy(n => n.TenNCC), "MaNCC", "TenNCC", sp.MaNCC);
            ViewBag.MaLoaiSP = new SelectList(db.LoaiSanPhams.OrderBy(n => n.MaLoaiSP), "MaLoaiSP", "TenLoai", sp.MaLoaiSP);
            ViewBag.MaNSX = new SelectList(db.NhaSanXuats.OrderBy(n => n.MaNSX), "MaNSX", "TenNSX", sp.MaNSX);
            return View(sp);
        }
        [ValidateInput(false)]
        [HttpPost]
        public ActionResult ChinhSua(SanPham model)
        {

            ViewBag.MaNCC = new SelectList(db.NhaCungCaps.OrderBy(n => n.TenNCC), "MaNCC", "TenNCC", model.MaNCC);
            ViewBag.MaLoaiSP = new SelectList(db.LoaiSanPhams.OrderBy(n => n.MaLoaiSP), "MaLoaiSP", "TenLoai", model.MaLoaiSP);
            ViewBag.MaNSX = new SelectList(db.NhaSanXuats.OrderBy(n => n.MaNSX), "MaNSX", "TenNSX", model.MaNSX);
            //Nếu dữ liệu đầu vào chắn chắn ok 
            db.Entry(model).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Xoa(int? id)
        {

            //Lấy sản phẩm cần chỉnh sửa dựa vào id
            if (id == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            SanPham sp = db.SanPhams.SingleOrDefault(n => n.MaSP == id);
            if (sp == null)
            {
                return HttpNotFound();
            }

            //Load dropdownlist nhà cung cấp và dropdownlist loại sp, mã nhà sản xuất
            ViewBag.MaNCC = new SelectList(db.NhaCungCaps.OrderBy(n => n.TenNCC), "MaNCC", "TenNCC", sp.MaNCC);
            ViewBag.MaLoaiSP = new SelectList(db.LoaiSanPhams.OrderBy(n => n.MaLoaiSP), "MaLoaiSP", "TenLoai", sp.MaLoaiSP);
            ViewBag.MaNSX = new SelectList(db.NhaSanXuats.OrderBy(n => n.MaNSX), "MaNSX", "TenNSX", sp.MaNSX);
            return View(sp);
        }

        [HttpPost]
        public ActionResult Xoa(int id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            SanPham model = db.SanPhams.SingleOrDefault(n => n.MaSP == id);
            if (model == null)
            {
                return HttpNotFound();
            }
            db.SanPhams.Remove(model);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (db != null)
                    db.Dispose();
                db.Dispose();
            }
            base.Dispose(disposing);
        }





    }
}

WebSiteDT/WebSiteDT/WebSiteDT/Views/QuanLySanPham/ChinhSua.cshtml
@model WebSiteDT.Models.SanPham


@{
    ViewBag.Title = "ChinhSua";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

@*Bước 1: Sử dụng control datetimepicker chèn 3 file script*@
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" href="/resources/demos/style.css">
@*Bước 1 khi sử dụng control editor tinymce*@
<script src="~/Content/tinymce/js/tinymce/tinymce.min.js"></script>
<script type="text/javascript">
    tinymce.init({
        selector: ".textarea",
        //plugins: [
        //    "advlist autolink lists link image charmap print preview anchor",
        //    "searchreplace visualblocks code fullscreen",
        //    "insertdatetime media table contextmenu paste"
        //],
        toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
    });
</script>


@*Bước 2: Xây dựng 1 function để điều hướng thẻ html theo dạng control datepicker*@
<script>
    $(function () {
        $("#datepicker").datepicker();
    });
</script>



<div class="container-fluid">
    <div class="row">
        <div class="col-md-6 p-b-10">
            <div class="overview-wrap">
                <h2 class="title-1">Chỉnh sửa sản phẩm</h2>
                <h3 class="au-btn au-btn-icon">
                    <i class="zmdi zmdi-plus"></i>
                    @*@Html.ActionLink("Thêm quyền", "ThemQuyen", null, new { @class = "btn btn-primary" })*@
                    @Html.ActionLink("Trở về", "Index")
                </h3>
            </div>
        </div>
    </div>


            @using (Html.BeginForm("ChinhSua", "QuanLySanPham", FormMethod.Post, new { @enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                <div class="form-horizontal">
                    @Html.ValidationSummary(true)
                    @Html.Hidden("MaSP", Model.MaSP);

                    <div class="form-group">
                        <label for="" class="col-sm-2 col-form-label">Tên sản phẩm</label>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.TenSP)
                            @Html.ValidationMessageFor(model => model.TenSP)
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="" class="col-sm-2 col-form-label">Đơn giá</label>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.DonGia)
                            @Html.ValidationMessageFor(model => model.DonGia)
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="" class="col-sm-2 col-form-label">Ngày cập nhật</label>
                        <div class="col-md-10">
                            @if (Model.NgayCapNhap != null)
                            {
                                <input type="date" name="@Model.NgayCapNhap.Value.ToString("dd/MM/yyyy")" id="datepicker" />
                                @*@Html.TextBox("NgayCapNhap", Model.NgayCapNhap.Value.ToString("dd/MM/yyyy"), new { id = "datepicker", @class = "date" })*@
                                @Html.ValidationMessageFor(model => model.NgayCapNhap)
                            }
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="" class="col-sm-2 col-form-label">Cấu hình</label>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.CauHinh)
                            @Html.ValidationMessageFor(model => model.CauHinh)
                        </div>
                    </div>


                    <div class="form-group">

                        <label for="" class="col-sm-2 col-form-label">Số lượng tồn</label>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.SoLuongTon)
                            @Html.ValidationMessageFor(model => model.SoLuongTon)
                        </div>
                    </div>

                    <div class="form-group">
                        @*@Html.LabelFor(model => model.LuotXem, new { @class = "control-label col-md-2" })*@
                        <label for="" class="col-sm-2 col-form-label">Lượt xem</label>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.LuotXem)
                            @Html.ValidationMessageFor(model => model.LuotXem)
                        </div>
                    </div>

                    <div class="form-group">
                        @*@Html.LabelFor(model => model.LuotBinhChon, new { @class = "control-label col-md-2" })*@
                        <label for="" class="col-sm-2 col-form-label">Lượt bình chọn</label>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.LuotBinhChon)
                            @Html.ValidationMessageFor(model => model.LuotBinhChon)
                        </div>
                    </div>

                    <div class="form-group">
                        @*@Html.LabelFor(model => model.LuotBinhLuan, new { @class = "control-label col-md-2" })*@
                        <label for="" class="col-sm-2 col-form-label">Lượt bình luận</label>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.LuotBinhLuan)
                            @Html.ValidationMessageFor(model => model.LuotBinhLuan)
                        </div>
                    </div>

                    <div class="form-group">
                        @*@Html.LabelFor(model => model.SoLanMua, new { @class = "control-label col-md-2" })*@
                        <label for="" class="col-sm-2 col-form-label">Số lần mua</label>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.SoLanMua)
                            @Html.ValidationMessageFor(model => model.SoLanMua)
                        </div>
                    </div>

                    <div class="form-group">
                        @*@Html.LabelFor(model => model.Moi, new { @class = "control-label col-md-2" })*@
                        <label for="" class="col-sm-2 col-form-label">Mới</label>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Moi)

                        </div>
                    </div>
                    @*Để load đúng dữ liệu của dropdownlist thì các bạn cần truyền đúng tên (name) đúng với tên viewbag*@
                    <div class="form-group">
                        @*@Html.LabelFor(model => model.MaNCC, new { @class = "control-label col-md-2" })*@
                        <label for="" class="col-sm-2 col-form-label">Nhà cung cấp</label>
                        <div class="col-md-3">
                            @Html.DropDownList("MaNCC", null, new { @class = "form-control" })

                        </div>
                    </div>

                    <div class="form-group">
                      
                        <label for="" class="col-sm-2 col-form-label">Nhà sản xuất</label>
                        <div class="col-md-3">
                            @Html.DropDownList("MaNSX", null, new { @class = "form-control" })

                        </div>
                    </div>

                    <div class="form-group">
                        <label for="" class="col-sm-2 col-form-label">Mã loại sản phẩm</label>
                        <div class="col-md-3">
                            @Html.DropDownList("MaLoaiSP", null, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.MaLoaiSP)
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="" class="col-sm-2 col-form-label">Đã xóa</label>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.DaXoa)
                            @Html.ValidationMessageFor(model => model.DaXoa)
                        </div>
                    </div>
                    @*Bước 2: Tạo 1 thẻ input với type = "file"> để lưu giá trị hình ảnh*@
                    <div class="form-group">
                        <label for="" class="col-sm-2 col-form-label">Hình ảnh</label>
                        <div class="col-md-10">
                            <input id="HinhAnh" name="HinhAnh" type="file" />
                            <span style="color:red;">@ViewBag.upload </span>
                            <br />
                            <img src="@Url.Content("~/Content/HinhAnhSP/"+Model.HinhAnh)" width="250" height="100" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="" class="col-sm-2 col-form-label">Hình ảnh 1</label>
                        <div class="col-md-10">
                            <input id="HinhAnh" name="HinhAnh" type="file" />
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="" class="col-sm-2 col-form-label">Hình ảnh 2</label>
                        <div class="col-md-10">
                            <input id="HinhAnh" name="HinhAnh" type="file" />
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="" class="col-sm-2 col-form-label">Hình ảnh 3</label>
                        <div class="col-md-10">
                            <input id="HinhAnh" name="HinhAnh" type="file" />
                        </div>
                    </div>

                    <div class="form-group">
                        <label for="" class="col-sm-2 col-form-label">Hình ảnh 4</label>
                        <div class="col-md-10">
                            <input id="HinhAnh" name="HinhAnh" type="file" />
                        </div>
                    </div>
                    <div class="form-group">
                        <label for="" class="col-sm-2 col-form-label">Mô tả</label>
                        <div class="col-md-10">
                            <textarea name="MoTa" class="textarea">@Model.MoTa</textarea>
                            @Html.ValidationMessageFor(model => model.MoTa)
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Lưu" class="btn btn-success" />
                        </div>
                    </div>
                </div>
            }

</div>

WebSiteDT/WebSiteDT/WebSiteDT/Views/QuanLySanPham/Index.cshtml
@using WebSiteDT.Models;
@model IEnumerable<SanPham>


@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
    //Khởi tạo control WebGrid
    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 5);
}
<div class="container-fluid">
    <div class="row">
        <div class="col-md-12 p-b-10">
            <div class="overview-wrap">
                <h2 class="title-1">Quản lý sản phẩm</h2>
                <h3 class="au-btn au-btn-icon">
                    <i class="zmdi zmdi-plus"></i>
                    @*@Html.ActionLink("Thêm quyền", "ThemQuyen", null, new { @class = "btn btn-primary" })*@
                    @Html.ActionLink("Thêm sản phẩm", "TaoMoi", null, new { @class = "btn btn-primary" })
                </h3>
            </div>
        </div>
    </div>
</div>



@*@Html.ActionLink("Thêm sản phẩm", "TaoMoi", null, new { @class = "btn btn-success" })
<br /><br />*@
@*Thể hiện dữ liệu thông qua control webGrid*@
@grid.GetHtml(
    tableStyle: "divTable table table-borderless table-striped table-earning",
    headerStyle: "gridHead" ,
    footerStyle: "gridFooter" ,
    rowStyle: "gridRow" ,
    alternatingRowStyle: "gridAltRow",
    columns: grid.Columns(
    grid.Column("MaSP", "Mã sản phẩm" ),
    grid.Column("TenSP", "Tên SP" ),
    grid.Column("HinhAnh", "Hình ảnh", format: p => @Html.Raw("<img width=\"150\" height=\"50\" src=\"../Content/HinhAnhSP/"+p.HinhAnh+"\">")),
    grid.Column(format: p=> @Html.ActionLink("Chỉnh sửa","ChinhSua",new {id=p.MaSP})),
    grid.Column(format: p => @Html.ActionLink("Xóa", "Xoa", new { id = p.MaSP }))
    ))


@*Css cho từng Style của table*@
<style>

    .divTable {
        width: 100%;
        border: 1px solid #999999;
    }

        .divTable td {
            border: 1px solid #999999;
        }

    .gridHead {
        background-color: Green;
    }

        .gridHead > th > a {
            color: #fff;
        }

    .gridFooter {
        font-weight: bold;
    }
    /*.gridRow {
        color:#fff;
        background-color:blueviolet;
    }
    .gridAltRow {
        color:#fff;
        background-color:darkorange;
    }*/

</style>

WebSiteDT/WebSiteDT/WebSiteDT/Views/QuanLySanPham/TaoMoi.cshtml
@model WebSiteDT.Models.SanPham

@{
    ViewBag.Title = "TaoMoi";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

@*Bước 1: Sử dụng control datetimepicker chèn 3 file script*@
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
<link rel="stylesheet" href="/resources/demos/style.css">
@*Bước 1 khi sử dụng control editor tinymce*@
@*<script src="https://cloud.tinymce.com/stable/tinymce.min.js"></script>*@
<script src="~/Content/tinymce/js/tinymce/tinymce.min.js"></script>
<script type="text/javascript">
    tinymce.init({
        selector: ".textarea",
        //plugins: [
        //    "advlist autolink lists link image charmap print preview anchor",
        //    "searchreplace visualblocks code fullscreen",
        //    "insertdatetime media table contextmenu paste"
        //],
        toolbar: "insertfile undo redo | styleselect | bold italic | alignleft aligncenter alignright alignjustify | bullist numlist outdent indent | link image"
    });
</script>


@*Bước 2: Xây dựng 1 function để điều hướng thẻ html theo dạng control datepicker*@
<script>
    $(function () {
        $("#datepicker").datepicker();
    });
</script>

@*<div>
    @Html.ActionLink("Back to List", "Index")
</div>*@


<div class="container-fluid">
    <div class="row">
        <div class="col-md-6 p-b-10">
            <div class="overview-wrap">
                <h2 class="title-1">Thêm sản phẩm</h2>
                <h3 class="au-btn au-btn-icon">
                    <i class="zmdi zmdi-plus"></i>
                    @*@Html.ActionLink("Thêm quyền", "ThemQuyen", null, new { @class = "btn btn-primary" })*@
                    @Html.ActionLink("Trở về", "Index")
                </h3>
            </div>
        </div>
    </div>




            @using (Html.BeginForm("TaoMoi", "QuanLySanPham", FormMethod.Post, new { @enctype = "multipart/form-data" }))
            {
                @Html.AntiForgeryToken()
                <div class="form-horizontal">

                    @Html.ValidationSummary(true)

                    <span style="color:red;">@Html.Raw(ViewBag.upload as string) <br /> @Html.Raw(ViewBag.upload1 as string) </span>

                    <div class="form-group">
                        @*@Html.LabelFor(model => model.TenSP, new { @class = "control-label col-md-2" })*@
                        <label for="" class="col-sm-2 col-form-label">Tên sản phẩm</label>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.TenSP)
                            @Html.ValidationMessageFor(model => model.TenSP)
                        </div>
                    </div>

                    <div class="form-group">
                        @*@Html.LabelFor(model => model.DonGia, new { @class = "control-label col-md-2" })*@
                        <label for="" class="col-sm-2 col-form-label">Đơn giá</label>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.DonGia)
                            @Html.ValidationMessageFor(model => model.DonGia)
                        </div>
                    </div>
                    @*Bước 3: đặt thêm thuộc tính class cho thẻ textbox*@
                    <div class="form-group">
                        @*@Html.LabelFor(model => model.NgayCapNhap, new { @class = "control-label col-md-2" })*@
                        <label for="" class="col-sm-2 col-form-label">Ngày cập nhật</label>
                        <div class="col-md-10">
                            <input type="date" name="NgayCapNhat" id="datepicker" />
                            @*@Html.TextBox("NgayCapNhap","", new { @id = "datepicker" })*@
                            @Html.ValidationMessageFor(model => model.NgayCapNhap)
                        </div>
                    </div>

                    <div class="form-group">
                        @*@Html.LabelFor(model => model.CauHinh, new { @class = "control-label col-md-2" })*@
                        <label for="" class="col-sm-2 col-form-label">Cấu hình</label>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.CauHinh)
                            @Html.ValidationMessageFor(model => model.CauHinh)
                        </div>
                    </div>




                    <div class="form-group">
                        @*@Html.LabelFor(model => model.SoLuongTon, new { @class = "control-label col-md-2" })*@
                        <label for="" class="col-sm-2 col-form-label">Số lượng tồn</label>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.SoLuongTon)
                            @Html.ValidationMessageFor(model => model.SoLuongTon)
                        </div>
                    </div>

                 

                    <div class="form-group">
                        @*@Html.LabelFor(model => model.Moi, new { @class = "control-label col-md-2" })*@
                        <label for="" class="col-sm-2 col-form-label">Mới</label>
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Moi)

                        </div>
                    </div>
                    @*Để load đúng dữ liệu của dropdownlist thì các bạn cần truyền đúng tên (name) đúng với tên viewbag*@
                    <div class="form-group">
                        @*@Html.LabelFor(model => model.MaNCC, new { @class = "control-label col-md-2" })*@
                        <label for="" class="col-sm-2 col-form-label">Nhà cung cấp</label>
                        <div class="col-md-3">
                            @Html.DropDownList("MaNCC", null, new { @class = "form-control" })

                        </div>
                    </div>

                    <div class="form-group">
                        @*@Html.LabelFor(model => model.MaNSX, new { @class = "control-label col-md-2" })*@
                        <label for="" class="col-sm-2 col-form-label">Nhà sản xuất</label>
                        <div class="col-md-3">
                            @Html.DropDownList("MaNSX", null, new { @class = "form-control" })

                        </div>
                    </div>

                    <div class="form-group">
                        @*@Html.LabelFor(model => model.MaLoaiSP, new { @class = "control-label col-md-2" })*@
                        <label for="" class="col-sm-2 col-form-label">Loại sản phẩm</label>
                        <div class="col-md-3">
                            @Html.DropDownList("MaLoaiSP", null, new { @class = "form-control" })
                            @Html.ValidationMessageFor(model => model.MaLoaiSP)
                        </div>
                    </div>

                    <div class="form-group">
                        @*@Html.LabelFor(model => model.HinhAnh, new { @class = "control-label col-md-2" })*@
                        <label for="" class="col-sm-2 col-form-label">Hình ảnh</label>
                        <div class="col-md-10">
                            <input id="HinhAnh" name="HinhAnh" type="file" />

                            <br />

                        </div>
                    </div>
                    <div class="form-group">
                        @*@Html.LabelFor(model => model.HinhAnh1, new { @class = "control-label col-md-2" })*@
                        <label for="" class="col-sm-2 col-form-label">Hình ảnh 1</label>
                        <div class="col-md-10">
                            <input id="HinhAnh" name="HinhAnh" type="file" />
                        </div>
                    </div>

                    <div class="form-group">
                        @*@Html.LabelFor(model => model.HinhAnh2, new { @class = "control-label col-md-2" })*@
                        <label for="" class="col-sm-2 col-form-label">Hình ảnh 2</label>
                        <div class="col-md-10">
                            <input id="HinhAnh" name="HinhAnh" type="file" />
                        </div>
                    </div>

                    <div class="form-group">
                        @*@Html.LabelFor(model => model.HinhAnh3, new { @class = "control-label col-md-2" })*@
                        <label for="" class="col-sm-2 col-form-label">Hình ảnh 3</label>
                        <div class="col-md-10">
                            <input id="HinhAnh" name="HinhAnh" type="file" />
                        </div>
                    </div>

                    <div class="form-group">
                        @*@Html.LabelFor(model => model.HinhAnh4, new { @class = "control-label col-md-2" })*@
                        <label for="" class="col-sm-2 col-form-label">Hình ảnh 4</label>
                        <div class="col-md-10">
                            <input id="HinhAnh" name="HinhAnh" type="file" />
                        </div>
                    </div>
                    <div class="form-group">
                        @*@Html.LabelFor(model => model.MoTa, new { @class = "control-label col-md-2" })*@
                        <label for="" class="col-sm-2 col-form-label">Mô tả</label>
                        <div class="col-md-10">
                            <textarea name="MoTa" class="textarea"></textarea>
                            @Html.ValidationMessageFor(model => model.MoTa)
                        </div>
                    </div>
                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Tạo mới" class="btn btn-success" />
                        </div>
                    </div>
                </div>
            }

</div>