WebSiteDT/WebSiteDT/WebSiteDT/Controllers/QuanLyPhieuNhapController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using WebSiteDT.Models;

namespace WebSiteDT.Controllers
{
    public class QuanLyPhieuNhapController : Controller
    {
        // GET: QuanLyPhieuNhap
        private QuanLyBanHangEntities db = new QuanLyBanHangEntities();

        [HttpGet]
        public ActionResult NhapHang()
        {
            ViewBag.MaNCC = db.NhaCungCaps;
            ViewBag.ListSanPham = db.SanPhams;
            return View();
        }

        [HttpPost]
        public ActionResult NhapHang(PhieuNhap model, IEnumerable<ChiTietPhieuNhap> lstModel)
        {
            ViewBag.MaNCC = db.NhaCungCaps;
            ViewBag.ListSanPham = db.SanPhams;
            //Sau khi các bạn đã kiểm tra tất cả dữ liệu đầu vào
            //Gán đã xóa: False
            model.DaXoa = false;
            db.PhieuNhaps.Add(model);
            db.SaveChanges();
            //SaveChanges để lấy được mã phiếu nhập gán cho lstChiTietPhieuNhap
            SanPham sp;
            foreach (var item in lstModel)
            {
                //Cập nhật số lượng tồn
                sp = db.SanPhams.Single(n => n.MaSP == item.MaSP);
                sp.SoLuongTon += item.SoLuongNhap;
                //Gán mã phiếu nhập cho tất cả chi tiết phiếu nhập
                item.MaPN = model.MaPN;
            }
            db.ChiTietPhieuNhaps.AddRange(lstModel);
            db.SaveChanges();
            return View();
        }

        [HttpGet]
        public ActionResult DSSPHetHang()
        {
            //Danh sách sản phẩm gần hết hàng với số lượng tồn bé hơn hoặc bằng 5
            var lstSP = db.SanPhams.Where(n => n.DaXoa == false && n.SoLuongTon <= 5);
            return View(lstSP);
        }

        //Tạo 1 view phục vụ cho việc nhập từng sản phẩm
        [HttpGet]
        public ActionResult NhapHangDon(int? id)
        {
            ViewBag.MaNCC = new SelectList(db.NhaCungCaps.OrderBy(n => n.TenNCC), "MaNCC", "TenNCC");
            //Tương tự như trang chỉnh sửa sản phẩm nhưng ta không cần phải show hết các thuộc tính
            //Chỉ thuộc tính nào cần thiết mà thôi đó là số lượng tồn hình ảnh... thông tin hiển thị cần thiết
            if (id == null)
            {
                Response.StatusCode = 404;
                return null;
            }
            SanPham sp = db.SanPhams.SingleOrDefault(n => n.MaSP == id);
            if (sp == null)
            {
                return HttpNotFound();
            }
            return View(sp);
        }

        // Xử lý nhập hàng từng sản phẩm
        [HttpPost]
        public ActionResult NhapHangDon(PhieuNhap model, ChiTietPhieuNhap ctpn)
        {
            ViewBag.MaNCC = new SelectList(db.NhaCungCaps.OrderBy(n => n.TenNCC), "MaNCC", "TenNCC", model.MaNCC);
            //Sau khi các bạn đã kiểm tra tất cả dữ liệu đầu vào
            //Gán đã xóa: False
            model.NgayNhap = DateTime.Now;
            model.DaXoa = false;
            db.PhieuNhaps.Add(model);
            db.SaveChanges();
            //SaveChanges để lấy được mã phiếu nhập gán cho lstChiTietPhieuNhap
            ctpn.MaPN = model.MaPN;
            //Cập nhật tồn
            SanPham sp = db.SanPhams.Single(n => n.MaSP == ctpn.MaSP);
            sp.SoLuongTon += ctpn.SoLuongNhap;
            db.ChiTietPhieuNhaps.Add(ctpn);
            db.SaveChanges();
            return View(sp);
        }

        //Giải phóng biến cho vùng nhớ
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (db != null)
                    db.Dispose();
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebSiteDT/WebSiteDT/WebSiteDT/Views/QuanLyPhieuNhap/DSSPHetHang.cshtml
@model IEnumerable<WebSiteDT.Models.SanPham>


@{
    ViewBag.Title = "DSSPHetHang";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
    //Khởi tạo control WebGrid
    WebGrid grid = new WebGrid(source: Model, rowsPerPage: 5);
}

<h2>Danh sách các sản phẩm gần hết hàng</h2>
<br /><br />
@*Thể hiện dữ liệu thông qua control webGrid*@
@grid.GetHtml(
    tableStyle: "divTable table-borderless table-striped table-earning",
    headerStyle: "gridHead",
    footerStyle: "gridFooter",
    rowStyle: "gridRow",
    alternatingRowStyle: "gridAltRow",
    columns: grid.Columns(
    grid.Column("MaSP", "Mã sản phẩm"),
    grid.Column("TenSP", "Tên SP"),
    grid.Column("HinhAnh", "Hình ảnh", format: p => @Html.Raw("<img width=\"150\" height=\"50\" src=\"../Content/HinhAnhSP/" + p.HinhAnh + "\">")),
    grid.Column(format: p => @Html.ActionLink("Nhập hàng", "NhapHangDon", new { id = p.MaSP }, new {@target="_blank" }))

    ))


@*Css cho từng Style của table*@
<style>
    .divTable {
        width: 100%;
        border: 1px solid #999999;
    }

        .divTable td {
            border: 1px solid #999999;
        }

    .gridHead {
        background-color: Green;
    }

        .gridHead > th > a {
            color: #fff;
        }

    .gridFooter {
        font-weight: bold;
    }
    /*.gridRow {
        color:#fff;
        background-color:blueviolet;
    }
    .gridAltRow {
        color:#fff;
        background-color:darkorange;
    }*/
</style>

<style>
    .FooterAdmin {
        display: none;
    }
</style>

WebSiteDT/WebSiteDT/WebSiteDT/Views/QuanLyPhieuNhap/NhapHang.cshtml
@using WebSiteDT.Models;
@model  PhieuNhap


@{
    ViewBag.Title = "NhapHang";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

@{
    IEnumerable<NhaCungCap> lstNCC = ViewBag.MaNCC as IEnumerable<NhaCungCap>;
}
@*Bước 1: Sử dụng control datetimepicker chèn 3 file script*@
<link rel="stylesheet" href="//code.jquery.com/ui/1.11.4/themes/smoothness/jquery-ui.css">
<script src="//code.jquery.com/jquery-1.10.2.js"></script>
<script src="//code.jquery.com/ui/1.11.4/jquery-ui.js"></script>
@*<link rel="stylesheet" href="resources/demos/style.css">*@

@*date time*@
<script>
    $(function () {
        $(".datepicker").datepicker();
    });
</script>

<div class="container-fluid">
    <div class="row">
        <div class="col-md-12 p-b-10">
            <div class="overview-wrap">
                <h2 class="title-1">Quản lý nhập hàng</h2>

            </div>
        </div>
    </div>


    @using (@Html.BeginForm())
    {
        <div class="row">
            <div class="ThongtinPhieuNhap col-md-12">
                <div class="col-md-2">
                    Nhà cung cấp
                </div>
                <div class="col-md-5">
                    @*Chọn nhà cung cấp*@
                    <select class="MaNCC" name="MaNCC">

                        @foreach (var item in lstNCC)
                        {
                            <option value="@item.MaNCC">@item.TenNCC</option>
                        }

                    </select>
                </div>
            </div>
        </div>
        <div class="clearfix"></div>
        <br />

        <div class="col-md-12">
            @*Ngày nhập*@
            <div class="col-md-2">
                Ngày nhập
            </div>
            <div class="col-md-5">
                @*<input name="NgayNhap" type="text" class="date" />*@
                <input type="date" name="NgayNhap" id="datepicker" />
            </div>
        </div>
        <div class="clearfix">  </div>
        <br /><br /><br />
        @*Phần chi tiết nhập hàng*@
        <table class="table table-borderless table-striped table-earning  tblChiTietPhieuNhap">
            @{IEnumerable<SanPham> lstSanPham = ViewBag.ListSanPham as IEnumerable<SanPham>;}
            @*Tạo ra 1 tr với nội dung nhập hàng của 1 sản phẩm*@
            <tr class="trAppend" style="display:none;">
                <td>
                    <select class="ddlSanPham" name="">
                        @foreach (var item in lstSanPham)
                        {
                            <option value="@item.MaSP"> @item.TenSP </option>
                        }
                    </select>
                </td>
                <td>
                    <input name="" class="txtDonGia" value="0" />
                </td>
                <td>
                    <input name="" class="txtSoLuong" value="0" />
                </td>
                <td>
                    <input class="btnDelete btn btn-danger" style="width:30px;height:30px" value="-" />
                </td>
            </tr>
            <tr class="trFirstChild" data-id="-1">
                <td>Sản phẩm</td>
                <td>Đơn giá nhập</td>
                <td>Số lượng nhập</td>
                <td></td>
            </tr>

        </table>
        @*Nút button thêm*@
        <input type="button" value="+" class="btn btn-success" id="btnAdd" />
        <input type="submit" value="Nhập hàng" class="btn btn-primary" id="btnNhapHang" />
    }


</div>






<script>

    $("#btnAdd").click(function () {
        // Lấy id của tr cuối cùng thuộc thẻ table có class = tblChiTietPhieuNhap
        //Bước 4: Phương thức find là tìm đến thẻ nào đó: ở đây là thẻ tr (:last-child) là thẻ tr cuối cùng trong thẻ tblChiTietPhieuNhap
        var id_cuoi = $(".tblChiTietPhieuNhap").find("tr:last-child").attr("data-id");
        i = parseInt(id_cuoi) + 1;
        //Bước 1: Nội dung phía trong thẻ trAppend
        var tdnoidung = $(".trAppend").html();
        //Bước 2:Tạo 1 thẻ tr bao ngoài nội dung
        var trnoidung = "<tr class=\"trAppended\" data-id=\"" +i+ "\">" + tdnoidung + "</tr>";
        ////Bước 3: Lấy thẻ table append vào 1 tr
        $(".tblChiTietPhieuNhap").append(trnoidung);
        loadIDLENTHE();

    });

    //Phương thức xử lý lấy thuộc tính attr từ thẻ tr gán xuống chỉ số phần tử các trong thuộc tính name của thẻ input
    function loadIDLENTHE() {
        $(".trAppended").each(function () {
            //Lấy thuộc tính data-id của thẻ tr hiện
            var id = $(this).attr("data-id");
            var nameMaSanPham = "[" + id + "].MaSP"; //Tạo ra mã sản phẩm
            var nameSoLuongNhap = "[" + id + "].SoLuongNhap"; //Tạo ra số lượng nhập
            var nameDonGiaNhap = "[" + id + "].DonGiaNhap";   //Tạo ra đơn giá nhập
            $(this).find(".ddlSanPham").attr("name", nameMaSanPham);//Gán name cho dropdownlist
            $(this).find(".txtDonGia").attr("name", nameDonGiaNhap);//Gán name đơn giá nhập
            $(this).find(".txtSoLuong").attr("name", nameSoLuongNhap);//Gán name số lượng nhập

        })
    };
    //Xử lý sự kiện xóa 1 dòng từ nút delete nằm bên trong thẻ tr
    //$("body").on("click", ".btnDelete", function () {
    //    //Xóa phần tử cha phía ngoài
    //    $(this).closest(".trAppended").remove();
    //});

    function CapNhapID()
    {   //Lấy lại tr 1
        var id_cuoi = $(".tblChiTietPhieuNhap").find(".trFirstChild").attr("data-id");
        i = parseInt(id_cuoi) + 1;

        $(".trAppended").each(function () {
            var id = i;
            $(this).attr("data-id", i);
            //Cập nhật lại id khi xóa
            var nameMaSanPham = "[" + id + "].MaSP"; //Tạo ra mã sản phẩm
            var nameSoLuongNhap = "[" + id + "].SoLuongNhap"; //Tạo ra số lượng nhập
            var nameDonGiaNhap = "[" + id + "].DonGiaNhap";   //Tạo ra đơn giá nhập
            $(this).find(".ddlSanPham").attr("name", nameMaSanPham);//Gán name cho dropdownlist
            $(this).find(".txtDonGia").attr("name", nameDonGiaNhap);//Gán name đơn giá nhập
            $(this).find(".txtSoLuong").attr("name", nameSoLuongNhap);//Gán name số lượng nhập
            i++;
        })
    }

    //Xử lý sự kiện xóa
    $("body").delegate(".btnDelete", "click", function () {
        //Xóa phần tử cha phía ngoài
        $(this).closest("tr").remove();
        CapNhapID();

    });

    $("#btnNhapHang").click(function () {

        if (kiemtraDonGia() == false)
        {
            //Nếu tồn tại 1 giá trị bất kỳ thuộc class đơn giá không phải số, thì ngăn không cho submit về server
            return false;
        }
        if (kiemtraSoLuong() == false)
        {
            return false;
        }

    });
    //Kiểm tra đơn giá
    function kiemtraDonGia() {
        var bl = true;
        //Duyệt vòng lặp each
        $(".txtDonGia").each(function () {
            var giatri = $(this).val();
            if (isNaN(giatri) == true) {
                alert("Đơn giá không hợp lệ!");
                bl = false;
                return bl;
            }
        });
        return bl;
    }
    function kiemtraSoLuong() {
        var bl = true;
        //Duyệt vòng lặp each
        $(".txtSoLuong").each(function () {
            var giatri = $(this).val();
            if (isNaN(giatri) == true) {
                alert("Số lượng không hợp lệ!");
                bl = false;
                return bl;
            }
        });
        return bl;
    }

</script>

WebSiteDT/WebSiteDT/WebSiteDT/Views/QuanLyPhieuNhap/NhapHangDon.cshtml
@using WebSiteDT.Models;
@model SanPham


@{
    ViewBag.Title = "NhapHangDon";
    Layout = "~/Views/Layout/AdminLayout.cshtml";
}

<legend>Nhập hàng cho sản phẩm: <b style="color: rgb(192,0,0)">@Model.TenSP</b> </legend>


<div class="row">
    <div class="col-md-3">
        <div class="imgSP">
            <img src="@Url.Content("~/Content/HinhAnhSP/"+Model.HinhAnh)" />
        </div>
    </div>
    <div class="col-md-9">
        <div class="ttSP">
            <h3>Hãng sản xuất: @Model.NhaSanXuat.TenNSX</h3>
            <h3>Loại sản phẩm: @Model.LoaiSanPham.TenLoai</h3>
            <h3>Số lượng tồn: @Model.SoLuongTon</h3>
        </div>
    </div>
</div>
<br />
<fieldset>
    <legend>Thông tin nhập hàng</legend>
</fieldset>
@using (Html.BeginForm("NhapHangDon", "QuanLyPhieuNhap"))
{
    @Html.Hidden("MaSP", Model.MaSP)
    <div class="row">
        <div class="col-md-4">
            @{var lstNCC = (SelectList)ViewBag.MaNCC;}
            Nhà cung cấp: @Html.DropDownList("MaNCC", lstNCC, new { @class = "MaNCC" })
        </div>
        <div class="col-md-4">
            Số lượng nhập : @Html.TextBox("SoLuongNhap")
        </div>
        <div class="col-md-4">
            Đơn giá nhập :@Html.TextBox("DonGiaNhap")
        </div>
        <div class="col-md-4">

        </div>
    </div>
    <div class="clear right" style="text-align:right;">
        <br />
        <input type="submit" class="btn btn-primary" value="Nhập hàng" />
    </div>
}
<style>
    .imgSP {
        border: 1px solid #999999;
        background-color: #fff;
        padding: 15px;
    }
</style>